GET http://localhost:8080/persons
###
GET http://localhost:8080/persons/645926dd90786aabcf03b69G
###
DELETE http://localhost:8080/persons/645ba091b0fc2aff0c25d5bb
###
POST http://localhost:8080/persons
Content-Type: application/json

{
    "name": "nostva",
    "age": 20,
    "email": "nostva9000@gmail.com",
    "gender": "male"
}
###
PUT http://localhost:8080/persons/645b852fff0f55e3742527c4
Content-Type: application/json

{
    "age": 20
}
####