version: '3.9'

services:
  # MongoDB service
  mongo_db:
    container_name: mongo_db_container
    image: mongo:latest
    restart: always
    volumes: 
      - mongo_db:/data/db

  # Node API service
  api:
    container_name: node_application
    build: .
    ports: 
     - 4000:8080
    environment:
      PORT: 8080
      MONGODB_URI: mongodb://mongo_db:27017/person
    depends_on:
      - mongo_db

volumes: 
  mongo_db: {}